CREATE TABLE IF NOT EXISTS trading_strategies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    rsi_period INTEGER,
    macd_fast_period INTEGER,
    macd_slow_period INTEGER,
    macd_signal_period INTEGER,
    adx_period INTEGER,
    bollinger_period INTEGER,
    bollinger_std_dev DOUBLE PRECISION,
    rsi_weight INTEGER,
    macd_weight INTEGER,
    adx_weight INTEGER,
    squeeze_weight INTEGER,
    active BOOLEAN,
    initial_capital DOUBLE PRECISION,
    min_entry_score INTEGER,
    rsi_neutral DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE,
    role VARCHAR(50) NOT NULL,
    available_funds DOUBLE PRECISION NOT NULL,
    total_invested DOUBLE PRECISION NOT NULL,
    current_value DOUBLE PRECISION NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    last_login TIMESTAMP,
    fyers_id VARCHAR(50) UNIQUE,
    fyers_token VARCHAR(500),
    fyers_connected BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(255) NOT NULL,
    trade_type VARCHAR(20),
    quantity INTEGER NOT NULL,
    entry_price DOUBLE PRECISION NOT NULL,
    exit_price DOUBLE PRECISION,
    entry_time TIMESTAMP NOT NULL,
    exit_time TIMESTAMP,
    stop_loss DOUBLE PRECISION,
    current_stop_loss DOUBLE PRECISION,
    atr DOUBLE PRECISION,
    highest_price DOUBLE PRECISION,
    is_paper_trade BOOLEAN NOT NULL,
    status VARCHAR(20),
    exit_reason VARCHAR(20),
    breakeven_moved BOOLEAN,
    realized_pnl DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS stock_screening_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(255) NOT NULL,
    signal_score INTEGER NOT NULL,
    grade VARCHAR(50) NOT NULL,
    entry_price DOUBLE PRECISION NOT NULL,
    stop_loss DOUBLE PRECISION,
    scan_time TIMESTAMP NOT NULL,
    approval_status VARCHAR(20) NOT NULL,
    analysis_reason VARCHAR(1000),
    macd_value DOUBLE PRECISION,
    rsi_value DOUBLE PRECISION,
    adx_value DOUBLE PRECISION,
    strategy_id BIGINT,
    CONSTRAINT fk_stock_screening_strategy FOREIGN KEY (strategy_id) REFERENCES trading_strategies(id)
);

CREATE TABLE IF NOT EXISTS watchlist_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    strategy_id BIGINT NOT NULL,
    CONSTRAINT fk_watchlist_strategy FOREIGN KEY (strategy_id) REFERENCES trading_strategies(id)
);

CREATE TABLE IF NOT EXISTS portfolio_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_id BIGINT,
    timestamp TIMESTAMP,
    total_equity DOUBLE PRECISION,
    available_balance DOUBLE PRECISION,
    day_pnl DOUBLE PRECISION,
    month_pnl DOUBLE PRECISION,
    CONSTRAINT fk_portfolio_metrics_strategy FOREIGN KEY (strategy_id) REFERENCES trading_strategies(id)
);

CREATE TABLE IF NOT EXISTS risk_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trading_date DATE NOT NULL,
    daily_loss DOUBLE PRECISION NOT NULL,
    consecutive_losses INTEGER NOT NULL,
    current_equity DOUBLE PRECISION NOT NULL,
    total_trades INTEGER,
    winning_trades INTEGER,
    losing_trades INTEGER,
    trading_halted BOOLEAN,
    halt_reason VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS sector_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(255) NOT NULL UNIQUE,
    sector VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode VARCHAR(20) NOT NULL,
    max_positions INTEGER NOT NULL,
    max_risk_per_trade_percent DOUBLE PRECISION NOT NULL,
    max_daily_loss_percent DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS circuit_breaker_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_time TIMESTAMP,
    reason VARCHAR(255),
    triggered_value DOUBLE PRECISION,
    action_taken VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS correlation_matrix (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    symbol_a VARCHAR(255),
    symbol_b VARCHAR(255),
    correlation DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS failed_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type VARCHAR(255) NOT NULL,
    details VARCHAR(255) NOT NULL,
    error_message TEXT,
    resolved BOOLEAN,
    retry_count INTEGER,
    timestamp TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS paper_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(255) NOT NULL UNIQUE,
    symbol VARCHAR(255) NOT NULL,
    side VARCHAR(50) NOT NULL,
    order_type VARCHAR(50) NOT NULL,
    quantity INTEGER NOT NULL,
    price DOUBLE PRECISION,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS paper_portfolio_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_trades INTEGER,
    winning_trades INTEGER,
    losing_trades INTEGER,
    win_rate DOUBLE PRECISION,
    net_pnl DOUBLE PRECISION,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS paper_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(255) NOT NULL,
    side VARCHAR(50) NOT NULL,
    quantity INTEGER NOT NULL,
    average_price DOUBLE PRECISION NOT NULL,
    last_price DOUBLE PRECISION,
    unrealized_pnl DOUBLE PRECISION,
    status VARCHAR(50) NOT NULL,
    entry_time TIMESTAMP NOT NULL,
    exit_time TIMESTAMP
);

CREATE TABLE IF NOT EXISTS paper_trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(255) NOT NULL,
    side VARCHAR(50) NOT NULL,
    quantity INTEGER NOT NULL,
    entry_price DOUBLE PRECISION NOT NULL,
    exit_price DOUBLE PRECISION,
    entry_time TIMESTAMP NOT NULL,
    exit_time TIMESTAMP,
    realized_pnl DOUBLE PRECISION,
    status VARCHAR(50) NOT NULL
);
