ALTER TABLE system_guard_state
    ADD COLUMN IF NOT EXISTS crisis_mode BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS crisis_reason TEXT,
    ADD COLUMN IF NOT EXISTS crisis_detail TEXT,
    ADD COLUMN IF NOT EXISTS crisis_started_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS crisis_until TIMESTAMPTZ;
